
- name: check python2.7.10
  shell: python -V | grep 2.7.10
  register: result  
  failed_when: result.rc not in [0, 1]
 
- name: get python2.7.10
  get_url: >-    
    url=https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
    dest=/usr/local/src/
  when: result.rc == 1

- name: unarchive
  unarchive: src=/usr/local/src/Python-2.7.10.tgz dest=/opt copy=no
  when: result.rc == 1

- name: configure
  shell: >-
    ./configure
    --prefix=/usr/local
    --enable-shared LDFLAGS=-Wl,-rpath,/usr/local/lib
    && make && make install    
    chdir=/opt/Python-2.7.10
  when: result.rc == 1
  
- name: get pip
  get_url: >-
    url=https://bootstrap.pypa.io/get-pip.py
    dest=/usr/local/src
  when: result.rc == 1

- name: check pip
  command: which pip
  failed_when: result.rc not in [0, 1]
  
- name: install pip
  command: python get-pip.py chdir=/usr/local/src
  when: result.rc == 1